services:
  panel_admin:
    container_name: panel_admin
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/usr/code/panel_admin
      - panel_admin:/var/lib/panel_admin
    ports:
      - ${PORT}:${PORT}
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: panel_admin
      SERVER_PORT: ${PORT}
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  panel_admin: